name: tests

on:
    push:
        branches:
            - "develop"
            - "develop/*"
        paths:
            - "src/**.ts"
            - "package.json"
            - "tsconfig.json"
            - ".github/workflows/**.yml"

jobs:
    test:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node-version: [14, 16, 18, 19]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2

            - name: Build
              run: |
                  npm install --silent
                  npm run build
                  ls -l ./

            - name: Testing
              run: |
                  npm test
