name: tests

on:
    push:
        branches:
            - develop
            - develop/*
        paths:
            - src/**.ts
            - package.json
            - tsconfig.json
            - .github/workflows/**.yml

jobs:
    test:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node-version: [16, 18]

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3

            - name: Testing
              run: |
                  npm install --silent
                  npm test
